### ISSUE TITLE
Optional parameter as async or vm_list does not reach the IM service in some cases

### ISSUE THREAD

**Issue by micafer** [indigo-dc/im-java-api#52] opened 2019-05-07 09:58 UTC

**Comment by micafer** [comment] 2019-05-07 10:00
Reported by Marica.
/cc @maricaantonacci

**Comment by alpegon** [comment] 2019-05-09 14:50
Fixed in PR #53

**Closed by alpegon** 2019-05-09 14:50 UTC

**Comment by maricaantonacci** [comment] 2019-05-10 11:10
Hi @alpegon and @micafer 
I've just made a test with the fixed version of the library and the problem is solved as far as I can see.

Thank you very much!
